// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ItemInput struct {
	ItemID   string  `json:"itemId"`
	Name     string  `json:"name"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
}

type Mutation struct {
}

type Query struct {
}
