package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"procurement-app-backend/handlers"
	"procurement-app-backend/models"
	"time"

	// "go.mongodb.org/mongo-driver/bson/primitive"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

var collection *mongo.Collection

// Initialize the collection
func init() {
	// Replace "your_database_name" and "your_collection_name" with your actual database and collection names
	clientOptions := options.Client().ApplyURI("mongodb://localhost:27017")
	client, err := mongo.Connect(context.Background(), clientOptions)
	if err != nil {
		panic(err)
	}
	collection = client.Database("procurementdb").Collection("purchaseorders")
}

// CreatePurchaseOrder is the resolver for the createPurchaseOrder field.
func (r *mutationResolver) CreatePurchaseOrder(ctx context.Context, userID string, items []*models.ItemInput) (*models.PurchaseOrder, error) {
	// panic(fmt.Errorf("not implemented: CreatePurchaseOrder - createPurchaseOrder"))
	var itemList []models.Item
	totalAmount := 0.0
	for _, item := range items {
		totalAmount += float64(item.Quantity) * item.Price
		itemList = append(itemList, models.Item{
			ItemID:   item.ItemID,
			Name:     item.Name,
			Quantity: item.Quantity,
			Price:    item.Price,
		})
	}

	purchaseOrder := &models.PurchaseOrder{
		OrderID:     primitive.NewObjectID().Hex(),
		UserID:      userID,
		Items:       itemList,
		TotalAmount: totalAmount,
		CreatedAt:   time.Now(),
	}

	_, err := collection.InsertOne(ctx, purchaseOrder)
	if err != nil {
		return nil, err
	}

	// go utils.SendEmail(userID, "Purchase Order Created", "Your purchase order has been successfully created.")

	return purchaseOrder, nil
}

// GenerateReport is the resolver for the generateReport field.
func (r *mutationResolver) GenerateReport(ctx context.Context, orderID string) (*models.Report, error) {
	panic(fmt.Errorf("not implemented: GenerateReport - generateReport"))
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, name string, email string, password string) (*models.User, error) {
	// panic(fmt.Errorf("not implemented: Register - register"))
	return handlers.Register(ctx, name, email, password)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))
	return handlers.Login(ctx, email, password)
}

// CreatedAt is the resolver for the createdAt field.
func (r *purchaseOrderResolver) CreatedAt(ctx context.Context, obj *models.PurchaseOrder) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// GetPurchaseOrders is the resolver for the getPurchaseOrders field.
func (r *queryResolver) GetPurchaseOrders(ctx context.Context) ([]*models.PurchaseOrder, error) {
	panic(fmt.Errorf("not implemented: GetPurchaseOrders - getPurchaseOrders"))
}

// GetReport is the resolver for the getReport field.
func (r *queryResolver) GetReport(ctx context.Context, orderID string) (*models.Report, error) {
	panic(fmt.Errorf("not implemented: GetReport - getReport"))
}

// GeneratedAt is the resolver for the generatedAt field.
func (r *reportResolver) GeneratedAt(ctx context.Context, obj *models.Report) (string, error) {
	panic(fmt.Errorf("not implemented: GeneratedAt - generatedAt"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PurchaseOrder returns PurchaseOrderResolver implementation.
func (r *Resolver) PurchaseOrder() PurchaseOrderResolver { return &purchaseOrderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Report returns ReportResolver implementation.
func (r *Resolver) Report() ReportResolver { return &reportResolver{r} }

type mutationResolver struct{ *Resolver }
type purchaseOrderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reportResolver struct{ *Resolver }
